import sublime, sublime_plugin
import re

def match(rex, str):
    m = rex.match(str)
    if m:
        return m.group(0)
    else:
        return None

class ModifierCompletions(sublime_plugin.EventListener):
    def on_query_completions(self, view, prefix, locations):
        # Only trigger within HTML
        if not view.match_selector(locations[0],
                "text.html - source"):
            return []

        pt = locations[0] - len(prefix) - 1
        ch = view.substr(sublime.Region(pt, pt + 1))
        if ch != ' ':
            return []

        return ([
            # global modifier
            ("_default\tMT modifier", "_default=\"$1\""),
            ("capitalize\tMT modifier", "capitalize=\"${1:1}\""),
            ("cat\tMT modifier", "cat=\"$1\""),
            ("count_characters\tMT modifier", "count_characters=\"${1:1}\""),
            ("count_paragraphs\tMT modifier", "count_paragraphs=\"${1:1}\""),
            ("count_words\tMT modifier", "count_words=\"${1:1}\""),
            ("decode_html\tMT modifier", "decode_html=\"${1:1}\""),
            ("decode_xml\tMT modifier", "decode_xml=\"${1:1}\""),
            ("dirify\tMT modifier", "dirify=\"${1:1}\""),
            ("encode_html\tMT modifier", "encode_html=\"${1:1}\""),
            ("encode_js\tMT modifier", "encode_js=\"${1:1}\""),
            ("encode_php\tMT modifier", "encode_php=\"${1:1}\""),
            ("encode_sha1\tMT modifier", "encode_sha1=\"${1:1}\""),
            ("encode_url\tMT modifier", "encode_url=\"${1:1}\""),
            ("encode_xml\tMT modifier", "encode_xml=\"${1:1}\""),
            ("escape\tMT modifier", "escape=\"$1\""),
            ("filters\tMT modifier", "filters=\"$1\""),
            ("indent\tMT modifier", "indent=\"${1:1}\""),
            ("lower_case\tMT modifier", "lower_case=\"${1:1}\""),
            ("ltrim\tMT modifier", "ltrim=\"${1:1}\""),
            ("mteval\tMT modifier", "mteval=\"${1:1}\""),
            ("nl2br\tMT modifier", "nl2br=\"$1\""),
            ("nofollowfy\tMT modifier", "nofollowfy=\"${1:1}\""),
            ("numify\tMT modifier", "numify=\"${1:1}\""),
            ("regex_replace\tMT modifier", "regex_replace=\"/${1:foo}/\",\"bar\""),
            ("remove_html\tMT modifier", "remove_html=\"${1:1}\""),
            ("replace\tMT modifier", "replace=\"${1:foo}\",\"bar\""),
            ("rtrim\tMT modifier", "rtrim=\"${1:1}\""),
            ("sanitize\tMT modifier", "sanitize=\"${1:1}\""),
            ("setvar\tMT modifier", "setvar=\"$1\""),
            ("smart_dashes\tMT modifier", "smart_dashes=\"${1:1}\""),
            ("smart_ellipses\tMT modifier", "smart_ellipses=\"${1:1}\""),
            ("smart_quotes\tMT modifier", "smart_quotes=\"${1:1}\""),
            ("smarty_pants\tMT modifier", "smarty_pants=\"${1:1}\""),
            ("space_pad\tMT modifier", "space_pad=\"$1\""),
            ("spacify\tMT modifier", "spacify=\"$1\""),
            ("spam_protect\tMT modifier", "spam_protect=\"${1:1}\""),
            ("sprintf\tMT modifier", "sprintf=\"$1\""),
            ("string_format\tMT modifier", "string_format=\"$1\""),
            ("strip\tMT modifier", "strip=\"$1\""),
            ("strip_linefeeds\tMT modifier", "strip_linefeeds=\"${1:1}\""),
            ("strip_tags\tMT modifier", "strip_tags=\"${1:1}\""),
            ("trim\tMT modifier", "trim=\"$1\""),
            ("trim_to\tMT modifier", "trim_to=\"${1:5+...}\""),
            ("upper_case\tMT modifier", "upper_case=\"${1:1}\""),
            ("wrap_text\tMT modifier", "wrap_text=\"$1\""),
            ("zero_pad\tMT modifier", "zero_pad=\"$1\""),

            # limit
            ("limit\tMT modifier", "limit=\"${1:1}\""),
            ("lastn\tMT modifier", "lastn=\"${1:0}\""),
            ("offset\tMT modifier", "offset=\"${1:10}\""),

            # sort_by
            ("sort_by=\"authored_on\"\tMT modifier", "sort_by=\"${1:authored_on}\""),
            ("sort_by=\"created_on\"\tMT modifier", "sort_by=\"${1:created_on}\""),
            ("sort_by=\"modified_on\"\tMT modifier", "sort_by=\"${1:modified_on}\""),
            ("sort_by=\"user_custom\"\tMT modifier", "sort_by=\"${1:user_custom}\""),
            ("sort_order\tMT modifier", "sort_order=\"${1:ascend|descend}\""),

            # category
            ("include_current\tMT modifier", "include_current=\"${1:1}\""),
            ("top\tMT modifier", "top=\"${1:1}\""),
            ("category\tMT modifier", "category=\"$1\""),
            ("glue\tMT modifier", "glue=\"$1\""),
            ("type\tMT modifier", "type=\"${1:primary}\""),
            ("show_empty\tMT modifier", "show_empty=\"${1:1}\""),

            # target
            ("blog_ids\tMT modifier", "blog_ids=\"${1:all|children|siblings}\""),
            ("include_blogs\tMT modifier", "include_blogs=\"${1:all|children|siblings}\""),
            ("include_with_website\tMT modifier", "include_with_website=\"${1:1}\""),
            ("exclude_blogs\tMT modifier", "exclude_blogs=\"$1\""),

            # date format
            ("format=\"%Y.%m.%d(%a) %H:%M:%S\"\tMT modifier", "format=\"${1:%Y.%m.%d(%a) %H:%M:%S}\""),

            # if
            ("name\tMT modifier", "name=\"$1\""),
            ("like\tMT modifier", "like=\"$1\""),
            ("eq\tMT modifier", "eq=\"$1\""),
            ("ne\tMT modifier", "ne=\"$1\""),
            ("lt\tMT modifier", "lt=\"$1\""),
            ("gt\tMT modifier", "gt=\"$1\""),
            ("le\tMT modifier", "le=\"$1\""),
            ("ge\tMT modifier", "ge=\"$1\""),
            ("tag\tMT modifier", "tag=\"$1\""),
            ("op\tMT modifier", "op=\"${1:+|-|*|/|%|++|--}\""),
            ("index\tMT modifier", "index=\"$1\""),
            ("key\tMT modifier", "key=\"$1\""),
            ("function\tMT modifier", "function=\"${1:pop|shift|count()}\""),
            ("value\tMT modifier", "value=\"$1\"")
        ], sublime.INHIBIT_WORD_COMPLETIONS | sublime.INHIBIT_EXPLICIT_COMPLETIONS)

class MtTagCompletions(sublime_plugin.EventListener):
    def on_query_completions(self, view, prefix, locations):
        # Only trigger within HTML
        if not view.match_selector(locations[0],
                "text.html - source"):
            return []

        pt = locations[0] - len(prefix) - 1
        ch = view.substr(sublime.Region(pt, pt + 1))
        if ch != '<':
            return []

        return ([
            # Block Tag
            ("mt:ActionStreams\tMT Block", "mt:ActionStreams$1>\n\t\n</mt:ActionStreams>"),
            ("mt:Actions\tMT Block", "mt:Actions$1>\n\t\n</mt:Actions>"),
            ("mt:ActionsComment\tMT Block", "mt:ActionsComment$1>\n\t\n</mt:ActionsComment>"),
            ("mt:ActionsEntry\tMT Block", "mt:ActionsEntry$1>\n\t\n</mt:ActionsEntry>"),
            ("mt:ActionsFavorite\tMT Block", "mt:ActionsFavorite$1>\n\t\n</mt:ActionsFavorite>"),
            ("mt:ActionsFooter\tMT Block", "mt:ActionsFooter$1>\n\t\n</mt:ActionsFooter>"),
            ("mt:ActionsHeader\tMT Block", "mt:ActionsHeader$1>\n\t\n</mt:ActionsHeader>"),
            ("mt:App:Form\tMT Block", "mt:App:Form$1>\n\t\n</mt:App:Form>"),
            ("mt:App:Listing\tMT Block", "mt:App:Listing$1>\n\t\n</mt:App:Listing>"),
            ("mt:App:Setting\tMT Block", "mt:App:Setting$1>\n\t\n</mt:App:Setting>"),
            ("mt:App:SettingGroup\tMT Block", "mt:App:SettingGroup$1>\n\t\n</mt:App:SettingGroup>"),
            ("mt:App:StatusMsg\tMT Block", "mt:App:StatusMsg$1>\n\t\n</mt:App:StatusMsg>"),
            ("mt:App:Widget\tMT Block", "mt:App:Widget$1>\n\t\n</mt:App:Widget>"),
            ("mt:ArchiveList\tMT Block", "mt:ArchiveList$1>\n\t\n</mt:ArchiveList>"),
            ("mt:ArchiveListFooter\tMT Block", "mt:ArchiveListFooter$1>\n\t\n</mt:ArchiveListFooter>"),
            ("mt:ArchiveListHeader\tMT Block", "mt:ArchiveListHeader$1>\n\t\n</mt:ArchiveListHeader>"),
            ("mt:ArchiveNext\tMT Block", "mt:ArchiveNext$1>\n\t\n</mt:ArchiveNext>"),
            ("mt:ArchivePrevious\tMT Block", "mt:ArchivePrevious$1>\n\t\n</mt:ArchivePrevious>"),
            ("mt:Archives\tMT Block", "mt:Archives$1>\n\t\n</mt:Archives>"),
            ("mt:Asset\tMT Block", "mt:Asset$1>\n\t\n</mt:Asset>"),
            ("mt:AssetIfTagged\tMT Block", "mt:AssetIfTagged$1>\n\t\n</mt:AssetIfTagged>"),
            ("mt:AssetIsFirstInRow\tMT Block", "mt:AssetIsFirstInRow$1>\n\t\n</mt:AssetIsFirstInRow>"),
            ("mt:AssetIsLastInRow\tMT Block", "mt:AssetIsLastInRow$1>\n\t\n</mt:AssetIsLastInRow>"),
            ("mt:AssetTags\tMT Block", "mt:AssetTags$1>\n\t\n</mt:AssetTags>"),
            ("mt:Assets\tMT Block", "mt:Assets$1>\n\t\n</mt:Assets>"),
            ("mt:AssetsFooter\tMT Block", "mt:AssetsFooter$1>\n\t\n</mt:AssetsFooter>"),
            ("mt:AssetsHeader\tMT Block", "mt:AssetsHeader$1>\n\t\n</mt:AssetsHeader>"),
            ("mt:AudioCustomFields\tMT Block", "mt:AudioCustomFields$1>\n\t\n</mt:AudioCustomFields>"),
            ("mt:AuthorCommentResponses\tMT Block", "mt:AuthorCommentResponses$1>\n\t\n</mt:AuthorCommentResponses>"),
            ("mt:AuthorComments\tMT Block", "mt:AuthorComments$1>\n\t\n</mt:AuthorComments>"),
            ("mt:AuthorCustomFields\tMT Block", "mt:AuthorCustomFields$1>\n\t\n</mt:AuthorCustomFields>"),
            ("mt:AuthorFollowers\tMT Block", "mt:AuthorFollowers$1>\n\t\n</mt:AuthorFollowers>"),
            ("mt:AuthorFollowing\tMT Block", "mt:AuthorFollowing$1>\n\t\n</mt:AuthorFollowing>"),
            ("mt:AuthorFollowingComments\tMT Block", "mt:AuthorFollowingComments$1>\n\t\n</mt:AuthorFollowingComments>"),
            ("mt:AuthorFollowingEntries\tMT Block", "mt:AuthorFollowingEntries$1>\n\t\n</mt:AuthorFollowingEntries>"),
            ("mt:AuthorFollowingFavorites\tMT Block", "mt:AuthorFollowingFavorites$1>\n\t\n</mt:AuthorFollowingFavorites>"),
            ("mt:AuthorHasEntry\tMT Block", "mt:AuthorHasEntry$1>\n\t\n</mt:AuthorHasEntry>"),
            ("mt:AuthorHasPage\tMT Block", "mt:AuthorHasPage$1>\n\t\n</mt:AuthorHasPage>"),
            ("mt:AuthorIfFollowed\tMT Block", "mt:AuthorIfFollowed$1>\n\t\n</mt:AuthorIfFollowed>"),
            ("mt:AuthorIfFollowing\tMT Block", "mt:AuthorIfFollowing$1>\n\t\n</mt:AuthorIfFollowing>"),
            ("mt:AuthorNext\tMT Block", "mt:AuthorNext$1>\n\t\n</mt:AuthorNext>"),
            ("mt:AuthorPrevious\tMT Block", "mt:AuthorPrevious$1>\n\t\n</mt:AuthorPrevious>"),
            ("mt:AuthorUserpicAsset\tMT Block", "mt:AuthorUserpicAsset$1>\n\t\n</mt:AuthorUserpicAsset>"),
            ("mt:Authors\tMT Block", "mt:Authors$1>\n\t\n</mt:Authors>"),
            ("mt:BlogIfCCLicense\tMT Block", "mt:BlogIfCCLicense$1>\n\t\n</mt:BlogIfCCLicense>"),
            ("mt:BlogIfCommentsOpen\tMT Block", "mt:BlogIfCommentsOpen$1>\n\t\n</mt:BlogIfCommentsOpen>"),
            ("mt:BlogParentWebsite\tMT Block", "mt:BlogParentWebsite$1>\n\t\n</mt:BlogParentWebsite>"),
            ("mt:BlogResultFooter\tMT Block", "mt:BlogResultFooter$1>\n\t\n</mt:BlogResultFooter>"),
            ("mt:BlogResultHeader\tMT Block", "mt:BlogResultHeader$1>\n\t\n</mt:>"),
            ("mt:Blogs\tMT Block", "mt:Blogs$1>\n\t\n</mt:Blogs>"),
            ("mt:Calendar\tMT Block", "mt:Calendar$1>\n\t\n</mt:Calendar>"),
            ("mt:CalendarIfBlank\tMT Block", "mt:CalendarIfBlank$1>\n\t\n</mt:CalendarIfBlank>"),
            ("mt:CalendarIfEntries\tMT Block", "mt:CalendarIfEntries$1>\n\t\n</mt:CalendarIfEntries>"),
            ("mt:CalendarIfNoEntries\tMT Block", "mt:CalendarIfNoEntries$1>\n\t\n</mt:CalendarIfNoEntries>"),
            ("mt:CalendarIfToday\tMT Block", "mt:CalendarIfToday$1>\n\t\n</mt:CalendarIfToday>"),
            ("mt:CalendarWeekFooter\tMT Block", "mt:CalendarWeekFooter$1>\n\t\n</mt:CalendarWeekFooter>"),
            ("mt:CalendarWeekHeader\tMT Block", "mt:CalendarWeekHeader$1>\n\t\n</mt:CalendarWeekHeader>"),
            ("mt:Categories\tMT Block", "mt:Categories$1>\n\t\n</mt:Categories>"),
            ("mt:CategoryCustomFields\tMT Block", "mt:CategoryCustomFields$1>\n\t\n</mt:CategoryCustomFields>"),
            ("mt:CategoryIfAllowPings\tMT Block", "mt:CategoryIfAllowPings$1>\n\t\n</mt:CategoryIfAllowPings>"),
            ("mt:CategoryNext\tMT Block", "mt:CategoryNext$1>\n\t\n</mt:CategoryNext>"),
            ("mt:CategoryPrevious\tMT Block", "mt:CategoryPrevious$1>\n\t\n</mt:CategoryPrevious>"),
            ("mt:CommentCustomFields\tMT Block", "mt:CommentCustomFields$1>\n\t\n</mt:CommentCustomFields>"),
            ("mt:CommentIfModerated\tMT Block", "mt:CommentIfModerated$1>\n\t\n</mt:CommentIfModerated>"),
            ("mt:CommentParent\tMT Block", "mt:CommentParent$1>\n\t\n</mt:CommentParent>"),
            ("mt:CommentReplies\tMT Block", "mt:CommentReplies$1>\n\t\n</mt:CommentReplies>"),
            ("mt:CommenterIfTrusted\tMT Block", "mt:CommenterIfTrusted$1>\n\t\n</mt:CommenterIfTrusted>"),
            ("mt:CommenterUserpicAsset\tMT Block", "mt:CommenterUserpicAsset$1>\n\t\n</mt:CommenterUserpicAsset>"),
            ("mt:Comments\tMT Block", "mt:Comments$1>\n\t\n</mt:Comments>"),
            ("mt:CommentsFooter\tMT Block", "mt:CommentsFooter$1>\n\t\n</mt:CommentsFooter>"),
            ("mt:CommentsHeader\tMT Block", "mt:CommentsHeader$1>\n\t\n</mt:CommentsHeader>"),
            ("mt:CustomFieldIsRequired\tMT Block", "mt:CustomFieldIsRequired$1>\n\t\n</mt:CustomFieldIsRequired>"),
            ("mt:DateFooter\tMT Block", "mt:DateFooter$1>\n\t\n</mt:DateFooter>"),
            ("mt:DateHeader\tMT Block", "mt:DateHeader$1>\n\t\n</mt:DateHeader>"),
            ("mt:Else\tMT Block", "mt:Else$1>\n\t\n</mt:Else>"),
            ("mt:ElseIf\tMT Block", "mt:ElseIf$1>\n\t\n</mt:ElseIf>"),
            ("mt:Entries\tMT Block", "mt:Entries$1>\n\t\n</mt:Entries>"),
            ("mt:EntriesFooter\tMT Block", "mt:EntriesFooter$1>\n\t\n</mt:EntriesFooter>"),
            ("mt:EntriesHeader\tMT Block", "mt:EntriesHeader$1>\n\t\n</mt:EntriesHeader>"),
            ("mt:EntriesWithSubCategories\tMT Block", "mt:EntriesWithSubCategories$1>\n\t\n</mt:EntriesWithSubCategories>"),
            ("mt:EntryAdditionalCategories\tMT Block", "mt:EntryAdditionalCategories$1>\n\t\n</mt:EntryAdditionalCategories>"),
            ("mt:EntryAssets\tMT Block", "mt:EntryAssets$1>\n\t\n</mt:EntryAssets>"),
            ("mt:EntryAuthorUserpicAsset\tMT Block", "mt:EntryAuthorUserpicAsset$1>\n\t\n</mt:EntryAuthorUserpicAsset>"),
            ("mt:EntryCategories\tMT Block", "mt:EntryCategories$1>\n\t\n</mt:EntryCategories>"),
            ("mt:EntryCustomFields\tMT Block", "mt:EntryCustomFields$1>\n\t\n</mt:EntryCustomFields>"),
            ("mt:EntryIfAllowComments\tMT Block", "mt:EntryIfAllowComments$1>\n\t\n</mt:EntryIfAllowComments>"),
            ("mt:EntryIfAllowPings\tMT Block", "mt:EntryIfAllowPings$1>\n\t\n</mt:EntryIfAllowPings>"),
            ("mt:EntryIfCategory\tMT Block", "mt:EntryIfCategory$1>\n\t\n</mt:EntryIfCategory>"),
            ("mt:EntryIfCommentsOpen\tMT Block", "mt:EntryIfCommentsOpen$1>\n\t\n</mt:EntryIfCommentsOpen>"),
            ("mt:EntryIfExtended\tMT Block", "mt:EntryIfExtended$1>\n\t\n</mt:EntryIfExtended>"),
            ("mt:EntryIfTagged\tMT Block", "mt:EntryIfTagged$1>\n\t\n</mt:EntryIfTagged>"),
            ("mt:EntryNext\tMT Block", "mt:EntryNext$1>\n\t\n</mt:EntryNext>"),
            ("mt:EntryPrevious\tMT Block", "mt:EntryPrevious$1>\n\t\n</mt:EntryPrevious>"),
            ("mt:EntryPrimaryCategory\tMT Block", "mt:EntryPrimaryCategory$1>\n\t\n</mt:EntryPrimaryCategory>"),
            ("mt:EntryTags\tMT Block", "mt:EntryTags$1>\n\t\n</mt:EntryTags>"),
            ("mt:Feed\tMT Block", "mt:Feed$1>\n\t\n</mt:Feed>"),
            ("mt:FeedEntries\tMT Block", "mt:FeedEntries$1>\n\t\n</mt:FeedEntries>"),
            ("mt:FileCustomFields\tMT Block", "mt:FileCustomFields$1>\n\t\n</mt:FileCustomFields>"),
            ("mt:FolderCustomFields\tMT Block", "mt:FolderCustomFields$1>\n\t\n</mt:FolderCustomFields>"),
            ("mt:FolderFooter\tMT Block", "mt:FolderFooter$1>\n\t\n</mt:FolderFooter>"),
            ("mt:FolderHeader\tMT Block", "mt:FolderHeader$1>\n\t\n</mt:FolderHeader>"),
            ("mt:FolderNext\tMT Block", "mt:FolderNext$1>\n\t\n</mt:FolderNext>"),
            ("mt:FolderPrevious\tMT Block", "mt:FolderPrevious$1>\n\t\n</mt:FolderPrevious>"),
            ("mt:Folders\tMT Block", "mt:Folders$1>\n\t\n</mt:Folders>"),
            ("mt:For\tMT Block", "mt:For$1>\n\t\n</mt:For>"),
            ("mt:HasNoParentCategory\tMT Block", "mt:HasNoParentCategory$1>\n\t\n</mt:HasNoParentCategory>"),
            ("mt:HasNoSubCategories\tMT Block", "mt:HasNoSubCategories$1>\n\t\n</mt:HasNoSubCategories>"),
            ("mt:HasParentCategory\tMT Block", "mt:HasParentCategory$1>\n\t\n</mt:HasParentCategory>"),
            ("mt:HasParentFolder\tMT Block", "mt:HasParentFolder$1>\n\t\n</mt:HasParentFolder>"),
            ("mt:HasSubCategories\tMT Block", "mt:HasSubCategories$1>\n\t\n</mt:HasSubCategories>"),
            ("mt:HasSubFolders\tMT Block", "mt:HasSubFolders$1>\n\t\n</mt:HasSubFolders>"),
            ("mt:If\tMT Block", "mt:If$1>\n\t\n</mt:If>"),
            ("mt:IfAllowCommentHTML\tMT Block", "mt:IfAllowCommentHTML$1>\n\t\n</mt:IfAllowCommentHTML>"),
            ("mt:IfAnonymousRecommendAllowed\tMT Block", "mt:IfAnonymousRecommendAllowed$1>\n\t\n</mt:IfAnonymousRecommendAllowed>"),
            ("mt:IfArchiveType\tMT Block", "mt:IfArchiveType$1>\n\t\n</mt:IfArchiveType>"),
            ("mt:IfArchiveTypeEnabled\tMT Block", "mt:IfArchiveTypeEnabled$1>\n\t\n</mt:IfArchiveTypeEnabled>"),
            ("mt:IfBlog\tMT Block", "mt:IfBlog$1>\n\t\n</mt:IfBlog>"),
            ("mt:IfCategory\tMT Block", "mt:IfCategory$1>\n\t\n</mt:IfCategory>"),
            ("mt:IfCommentParent\tMT Block", "mt:IfCommentParent$1>\n\t\n</mt:IfCommentParent>"),
            ("mt:IfCommentReplies\tMT Block", "mt:IfCommentReplies$1>\n\t\n</mt:IfCommentReplies>"),
            ("mt:IfCommenterIsAuthor\tMT Block", "mt:IfCommenterIsAuthor$1>\n\t\n</mt:IfCommenterIsAuthor>"),
            ("mt:IfCommenterIsEntryAuthor\tMT Block", "mt:IfCommenterIsEntryAuthor$1>\n\t\n</mt:IfCommenterIsEntryAuthor>"),
            ("mt:IfCommenterTrusted\tMT Block", "mt:IfCommenterTrusted$1>\n\t\n</mt:IfCommenterTrusted>"),
            ("mt:IfCommentsAccepted\tMT Block", "mt:IfCommentsAccepted$1>\n\t\n</mt:IfCommentsAccepted>"),
            ("mt:IfCommentsActive\tMT Block", "mt:IfCommentsActive$1>\n\t\n</mt:IfCommentsActive>"),
            ("mt:IfCommentsAllowed\tMT Block", "mt:IfCommentsAllowed$1>\n\t\n</mt:IfCommentsAllowed>"),
            ("mt:IfCommentsModerated\tMT Block", "mt:IfCommentsModerated$1>\n\t\n</mt:IfCommentsModerated>"),
            ("mt:IfCurrentPage\tMT Block", "mt:IfCurrentPage$1>\n\t\n</mt:IfCurrentPage>"),
            ("mt:IfDynamic\tMT Block", "mt:IfDynamic$1>\n\t\n</mt:IfDynamic>"),
            ("mt:IfFolder\tMT Block", "mt:IfFolder$1>\n\t\n</mt:IfFolder>"),
            ("mt:IfImageSupport\tMT Block", "mt:IfImageSupport$1>\n\t\n</mt:IfImageSupport>"),
            ("mt:IfIsAncestor\tMT Block", "mt:IfIsAncestor$1>\n\t\n</mt:IfIsAncestor>"),
            ("mt:IfIsDescendant\tMT Block", "mt:IfIsDescendant$1>\n\t\n</mt:IfIsDescendant>"),
            ("mt:IfLoggedIn\tMT Block", "mt:IfLoggedIn$1>\n\t\n</mt:IfLoggedIn>"),
            ("mt:IfMaxResultsCutoff\tMT Block", "mt:IfMaxResultsCutoff$1>\n\t\n</mt:IfMaxResultsCutoff>"),
            ("mt:IfMoreResults\tMT Block", "mt:IfMoreResults$1>\n\t\n</mt:IfMoreResults>"),
            ("mt:IfNeedEmail\tMT Block", "mt:IfNeedEmail$1>\n\t\n</mt:IfNeedEmail>"),
            ("mt:IfNonEmpty\tMT Block", "mt:IfNonEmpty$1>\n\t\n</mt:IfNonEmpty>"),
            ("mt:IfNonZero\tMT Block", "mt:IfNonZero$1>\n\t\n</mt:IfNonZero>"),
            ("mt:IfPingsAccepted\tMT Block", "mt:IfPingsAccepted$1>\n\t\n</mt:IfPingsAccepted>"),
            ("mt:IfPingsActive\tMT Block", "mt:IfPingsActive$1>\n\t\n</mt:IfPingsActive>"),
            ("mt:IfPingsAllowed\tMT Block", "mt:IfPingsAllowed$1>\n\t\n</mt:IfPingsAllowed>"),
            ("mt:IfPingsModerated\tMT Block", "mt:IfPingsModerated$1>\n\t\n</mt:IfPingsModerated>"),
            ("mt:IfPreviousResults\tMT Block", "mt:IfPreviousResults$1>\n\t\n</mt:IfPreviousResults>"),
            ("mt:IfRegistrationAllowed\tMT Block", "mt:IfRegistrationAllowed$1>\n\t\n</mt:IfRegistrationAllowed>"),
            ("mt:IfRegistrationNotRequired\tMT Block", "mt:IfRegistrationNotRequired$1>\n\t\n</mt:IfRegistrationNotRequired>"),
            ("mt:IfRegistrationRequired\tMT Block", "mt:IfRegistrationRequired$1>\n\t\n</mt:IfRegistrationRequired>"),
            ("mt:IfRequireCommentEmails\tMT Block", "mt:IfRequireCommentEmails$1>\n\t\n</mt:IfRequireCommentEmails>"),
            ("mt:IfStatic\tMT Block", "mt:IfStatic$1>\n\t\n</mt:IfStatic>"),
            ("mt:IfStraightSearch\tMT Block", "mt:IfStraightSearch$1>\n\t\n</mt:IfStraightSearch>"),
            ("mt:IfTagSearch\tMT Block", "mt:IfTagSearch$1>\n\t\n</mt:IfTagSearch>"),
            ("mt:IfTypeKeyToken\tMT Block", "mt:IfTypeKeyToken$1>\n\t\n</mt:IfTypeKeyToken>"),
            ("mt:IfWebsite\tMT Block", "mt:IfWebsite$1>\n\t\n</mt:IfWebsite>"),
            ("mt:Ignore\tMT Block", "mt:Ignore$1>\n\t\n</mt:Ignore>"),
            ("mt:ImageCustomFields\tMT Block", "mt:ImageCustomFields$1>\n\t\n</mt:ImageCustomFields>"),
            ("mt:IncludeBlock\tMT Block", "mt:IncludeBlock$1>\n\t\n</mt:IncludeBlock>"),
            ("mt:IndexList\tMT Block", "mt:IndexList$1>\n\t\n</mt:IndexList>"),
            ("mt:Loop\tMT Block", "mt:Loop$1>\n\t\n</mt:Loop>"),
            ("mt:MarkdownOptions\tMT Block", "mt:MarkdownOptions$1>\n\t\n</mt:MarkdownOptions>"),
            ("mt:MultiBlog\tMT Block", "mt:MultiBlog$1>\n\t\n</mt:MultiBlog>"),
            ("mt:MultiBlogIfLocalBlog\tMT Block", "mt:MultiBlogIfLocalBlog$1>\n\t\n</mt:MultiBlogIfLocalBlog>"),
            ("mt:MultiBlogLocalBlog\tMT Block", "mt:MultiBlogLocalBlog$1>\n\t\n</mt:MultiBlogLocalBlog>"),
            ("mt:NoSearch\tMT Block", "mt:NoSearch$1>\n\t\n</mt:NoSearch>"),
            ("mt:NoSearchResults\tMT Block", "mt:NoSearchResults$1>\n\t\n</mt:NoSearchResults>"),
            ("mt:OtherBlog\tMT Block", "mt:OtherBlog$1>\n\t\n</mt:OtherBlog>"),
            ("mt:OtherProfiles\tMT Block", "mt:OtherProfiles$1>\n\t\n</mt:OtherProfiles>"),
            ("mt:PageAssets\tMT Block", "mt:PageAssets$1>\n\t\n</mt:PageAssets>"),
            ("mt:PageCustomFields\tMT Block", "mt:PageCustomFields$1>\n\t\n</mt:PageCustomFields>"),
            ("mt:PageFolder\tMT Block", "mt:PageFolder$1>\n\t\n</mt:PageFolder>"),
            ("mt:PageIfTagged\tMT Block", "mt:PageIfTagged$1>\n\t\n</mt:PageIfTagged>"),
            ("mt:PageNext\tMT Block", "mt:PageNext$1>\n\t\n</mt:PageNext>"),
            ("mt:PagePrevious\tMT Block", "mt:PagePrevious$1>\n\t\n</mt:PagePrevious>"),
            ("mt:PageTags\tMT Block", "mt:PageTags$1>\n\t\n</mt:PageTags>"),
            ("mt:PagerBlock\tMT Block", "mt:PagerBlock$1>\n\t\n</mt:PagerBlock>"),
            ("mt:Pages\tMT Block", "mt:Pages$1>\n\t\n</mt:Pages>"),
            ("mt:PagesFooter\tMT Block", "mt:PagesFooter$1>\n\t\n</mt:PagesFooter>"),
            ("mt:PagesHeader\tMT Block", "mt:PagesHeader$1>\n\t\n</mt:PagesHeader>"),
            ("mt:ParentCategories\tMT Block", "mt:ParentCategories$1>\n\t\n</mt:ParentCategories>"),
            ("mt:ParentCategory\tMT Block", "mt:ParentCategory$1>\n\t\n</mt:ParentCategory>"),
            ("mt:ParentFolder\tMT Block", "mt:ParentFolder$1>\n\t\n</mt:ParentFolder>"),
            ("mt:ParentFolders\tMT Block", "mt:ParentFolders$1>\n\t\n</mt:ParentFolders>"),
            ("mt:PingEntry\tMT Block", "mt:PingEntry$1>\n\t\n</mt:PingEntry>"),
            ("mt:Pings\tMT Block", "mt:Pings$1>\n\t\n</mt:Pings>"),
            ("mt:PingsFooter\tMT Block", "mt:PingsFooter$1>\n\t\n</mt:PingsFooter>"),
            ("mt:PingsHeader\tMT Block", "mt:PingsHeader$1>\n\t\n</mt:PingsHeader>"),
            ("mt:PingsSent\tMT Block", "mt:PingsSent$1>\n\t\n</mt:PingsSent>"),
            ("mt:ProfileServices\tMT Block", "mt:ProfileServices$1>\n\t\n</mt:ProfileServices>"),
            ("mt:SearchResults\tMT Block", "mt:SearchResults$1>\n\t\n</mt:SearchResults>"),
            ("mt:Section\tMT Block", "mt:Section$1>\n\t\n</mt:Section>"),
            ("mt:SetHashVar\tMT Block", "mt:SetHashVar$1>\n\t\n</mt:SetHashVar>"),
            ("mt:SetVarBlock\tMT Block", "mt:SetVarBlock$1>\n\t\n</mt:SetVarBlock>"),
            ("mt:SetVarTemplate\tMT Block", "mt:SetVarTemplate$1>\n\t\n</mt:SetVarTemplate>"),
            ("mt:SetVars\tMT Block", "mt:SetVars$1>\n\t\n</mt:SetVars>"),
            ("mt:StreamActionRollup\tMT Block", "mt:StreamActionRollup$1>\n\t\n</mt:StreamActionRollup>"),
            ("mt:StreamActionTags\tMT Block", "mt:StreamActionTags$1>\n\t\n</mt:StreamActionTags>"),
            ("mt:SubCatIsFirst\tMT Block", "mt:SubCatIsFirst$1>\n\t\n</mt:SubCatIsFirst>"),
            ("mt:SubCatIsLast\tMT Block", "mt:SubCatIsLast$1>\n\t\n</mt:SubCatIsLast>"),
            ("mt:SubCategories\tMT Block", "mt:SubCategories$1>\n\t\n</mt:SubCategories>"),
            ("mt:SubFolders\tMT Block", "mt:SubFolders$1>\n\t\n</mt:SubFolders>"),
            ("mt:Tags\tMT Block", "mt:Tags$1>\n\t\n</mt:Tags>"),
            ("mt:TemplateCustomFields\tMT Block", "mt:TemplateCustomFields$1>\n\t\n</mt:TemplateCustomFields>"),
            ("mt:Textile\tMT Block", "mt:Textile$1>\n\t\n</mt:Textile>"),
            ("mt:TopLevelCategories\tMT Block", "mt:TopLevelCategories$1>\n\t\n</mt:TopLevelCategories>"),
            ("mt:TopLevelFolder\tMT Block", "mt:TopLevelFolder$1>\n\t\n</mt:TopLevelFolder>"),
            ("mt:TopLevelFolders\tMT Block", "mt:TopLevelFolders$1>\n\t\n</mt:TopLevelFolders>"),
            ("mt:TopLevelParent\tMT Block", "mt:TopLevelParent$1>\n\t\n</mt:TopLevelParent>"),
            ("mt:Unless\tMT Block", "mt:Unless$1>\n\t\n</mt:Unless>"),
            ("mt:VideoCustomFields\tMT Block", "mt:VideoCustomFields$1>\n\t\n</mt:VideoCustomFields>"),
            ("mt:WebsiteCustomFields\tMT Block", "mt:WebsiteCustomFields$1>\n\t\n</mt:WebsiteCustomFields>"),
            ("mt:WebsiteIfCCLicense\tMT Block", "mt:WebsiteIfCCLicense$1>\n\t\n</mt:WebsiteIfCCLicense>"),
            ("mt:WebsiteIfCommentsOpen\tMT Block", "mt:WebsiteIfCommentsOpen$1>\n\t\n</mt:WebsiteIfCommentsOpen>"),
            ("mt:Websites\tMT Block", "mt:Websites$1>\n\t\n</mt:Websites>"),

            # Function Tag
            ("mt:AdminCGIPath\tMT Function", "mt:AdminCGIPath$1 />"),
            ("mt:AdminScript\tMT Function", "mt:AdminScript$1 />"),
            ("mt:App:ActionBar\tMT Function", "mt:ActionBar$1 />"),
            ("mt:App:Link\tMT Function", "mt:App:Link$1 />"),
            ("mt:App:ListFilters\tMT Function", "mt:App:ListFilters$1 />"),
            ("mt:App:PageActions\tMT Function", "mt:App:PageActions$1 />"),
            ("mt:ArchiveCategory\tMT Function", "mt:ArchiveCategory$1 />"),
            ("mt:ArchiveCount\tMT Function", "mt:ArchiveCount$1 />"),
            ("mt:ArchiveDate\tMT Function", "mt:ArchiveDate$1 />"),
            ("mt:ArchiveDateEnd\tMT Function", "mt:ArchiveDateEnd$1 />"),
            ("mt:ArchiveFile\tMT Function", "mt:ArchiveFile$1 />"),
            ("mt:ArchiveLabel\tMT Function", "mt:ArchiveLabel$1 />"),
            ("mt:ArchiveLink\tMT Function", "mt:ArchiveLink$1 />"),
            ("mt:ArchiveTitle\tMT Function", "mt:ArchiveTitle$1 />"),
            ("mt:ArchiveType\tMT Function", "mt:ArchiveType$1 />"),
            ("mt:ArchiveTypeLabel\tMT Function", "mt:ArchiveTypeLabel$1 />"),
            ("mt:AssetAddedBy\tMT Function", "mt:AssetAddedBy$1 />"),
            ("mt:AssetCount\tMT Function", "mt:AssetCount$1 />"),
            ("mt:AssetDateAdded\tMT Function", "mt:AssetDateAdded$1 />"),
            ("mt:AssetDescription\tMT Function", "mt:AssetDescription$1 />"),
            ("mt:AssetFileExt\tMT Function", "mt:AssetFileExt$1 />"),
            ("mt:AssetFileName\tMT Function", "mt:AssetFileName$1 />"),
            ("mt:AssetFilePath\tMT Function", "mt:AssetFilePath$1 />"),
            ("mt:AssetID\tMT Function", "mt:AssetID$1 />"),
            ("mt:AssetLabel\tMT Function", "mt:AssetLabel$1 />"),
            ("mt:AssetLink\tMT Function", "mt:AssetLink$1 />"),
            ("mt:AssetMimeType\tMT Function", "mt:AssetMimeType$1 />"),
            ("mt:AssetProperty\tMT Function", "mt:AssetProperty$1 />"),
            ("mt:AssetRank\tMT Function", "mt:AssetRank$1 />"),
            ("mt:AssetScore\tMT Function", "mt:AssetScore$1 />"),
            ("mt:AssetScoreAvg\tMT Function", "mt:AssetScoreAvg$1 />"),
            ("mt:AssetScoreCount\tMT Function", "mt:AssetScoreCount$1 />"),
            ("mt:AssetScoreHigh\tMT Function", "mt:AssetScoreHigh$1 />"),
            ("mt:AssetScoreLow\tMT Function", "mt:AssetScoreLow$1 />"),
            ("mt:AssetThumbnailLink\tMT Function", "mt:AssetThumbnailLink$1 />"),
            ("mt:AssetThumbnailURL\tMT Function", "mt:AssetThumbnailURL$1 />"),
            ("mt:AssetType\tMT Function", "mt:AssetType$1 />"),
            ("mt:AssetURL\tMT Function", "mt:AssetURL$1 />"),
            ("mt:AtomScript\tMT Function", "mt:AtomScript$1 />"),
            ("mt:AudioCustomFieldDescription\tMT Function", "mt:AudioCustomFieldDescription$1 />"),
            ("mt:AudioCustomFieldName\tMT Function", "mt:AudioCustomFieldName$1 />"),
            ("mt:AudioCustomFieldValue\tMT Function", "mt:AudioCustomFieldValue$1 />"),
            ("mt:AuthorAuthIconURL\tMT Function", "mt:AuthorAuthIconURL$1 />"),
            ("mt:AuthorAuthType\tMT Function", "mt:AuthorAuthType$1 />"),
            ("mt:AuthorBasename\tMT Function", "mt:AuthorBasename$1 />"),
            ("mt:AuthorCommentCount\tMT Function", "mt:AuthorCommentCount$1 />"),
            ("mt:AuthorCustomFieldDescription\tMT Function", "mt:AuthorCustomFieldDescription$1 />"),
            ("mt:AuthorCustomFieldName\tMT Function", "mt:AuthorCustomFieldName$1 />"),
            ("mt:AuthorCustomFieldValue\tMT Function", "mt:AuthorCustomFieldValue$1 />"),
            ("mt:AuthorDisplayName\tMT Function", "mt:AuthorDisplayName$1 />"),
            ("mt:AuthorEmail\tMT Function", "mt:AuthorEmail$1 />"),
            ("mt:AuthorEntriesCount\tMT Function", "mt:AuthorEntriesCount$1 />"),
            ("mt:AuthorEntryCount\tMT Function", "mt:AuthorEntryCount$1 />"),
            ("mt:AuthorFollowLink\tMT Function", "mt:AuthorFollowLink$1 />"),
            ("mt:AuthorFollowersCount\tMT Function", "mt:AuthorFollowersCount$1 />"),
            ("mt:AuthorFollowingCount\tMT Function", "mt:AuthorFollowingCount$1 />"),
            ("mt:AuthorID\tMT Function", "mt:AuthorID$1 />"),
            ("mt:AuthorName\tMT Function", "mt:AuthorName$1 />"),
            ("mt:AuthorRank\tMT Function", "mt:AuthorRank$1 />"),
            ("mt:AuthorScore\tMT Function", "mt:AuthorScore$1 />"),
            ("mt:AuthorScoreAvg\tMT Function", "mt:AuthorScoreAvg$1 />"),
            ("mt:AuthorScoreCount\tMT Function", "mt:AuthorScoreCount$1 />"),
            ("mt:AuthorScoreHigh\tMT Function", "mt:AuthorScoreHigh$1 />"),
            ("mt:AuthorScoreLow\tMT Function", "mt:AuthorScoreLow$1 />"),
            ("mt:AuthorURL\tMT Function", "mt:AuthorURL$1 />"),
            ("mt:AuthorUnFollowLink\tMT Function", "mt:AuthorUnFollowLink$1 />"),
            ("mt:AuthorUserpic\tMT Function", "mt:AuthorUserpic$1 />"),
            ("mt:AuthorUserpicURL\tMT Function", "mt:AuthorUserpicURL$1 />"),
            ("mt:BlogArchiveURL\tMT Function", "mt:BlogArchiveURL$1 />"),
            ("mt:BlogCCLicenseImage\tMT Function", "mt:BlogCCLicenseImage$1 />"),
            ("mt:BlogCCLicenseURL\tMT Function", "mt:BlogCCLicenseURL$1 />"),
            ("mt:BlogCategoryCount\tMT Function", "mt:BlogCategoryCount$1 />"),
            ("mt:BlogCommentCount\tMT Function", "mt:BlogCommentCount$1 />"),
            ("mt:BlogCustomFieldDescription\tMT Function", "mt:BlogCustomFieldDescription$1 />"),
            ("mt:BlogCustomFieldName\tMT Function", "mt:BlogCustomFieldName$1 />"),
            ("mt:BlogCustomFieldValue\tMT Function", "mt:BlogCustomFieldValue$1 />"),
            ("mt:BlogCustomFields\tMT Function", "mt:BlogCustomFields$1 />"),
            ("mt:BlogDescription\tMT Function", "mt:BlogDescription$1 />"),
            ("mt:BlogEntryCount\tMT Function", "mt:BlogEntryCount$1 />"),
            ("mt:BlogFileExtension\tMT Function", "mt:BlogFileExtension$1 />"),
            ("mt:BlogHost\tMT Function", "mt:BlogHost$1 />"),
            ("mt:BlogID\tMT Function", "mt:BlogID$1 />"),
            ("mt:BlogLanguage\tMT Function", "mt:BlogLanguage$1 />"),
            ("mt:BlogName\tMT Function", "mt:BlogName$1 />"),
            ("mt:BlogPageCount\tMT Function", "mt:BlogPageCount$1 />"),
            ("mt:BlogPingCount\tMT Function", "mt:BlogPingCount$1 />"),
            ("mt:BlogRelativeURL\tMT Function", "mt:BlogRelativeURL$1 />"),
            ("mt:BlogSitePath\tMT Function", "mt:BlogSitePath$1 />"),
            ("mt:BlogTemplateSetID\tMT Function", "mt:BlogTemplateSetID$1 />"),
            ("mt:BlogThemeID\tMT Function", "mt:BlogThemeID$1 />"),
            ("mt:BlogTimezone\tMT Function", "mt:BlogTimezone$1 />"),
            ("mt:BlogURL\tMT Function", "mt:BlogURL$1 />"),
            ("mt:BuildTemplateID\tMT Function", "mt:BuildTemplateID$1 />"),
            ("mt:CCLicenseRDF\tMT Function", "mt:CCLicenseRDF$1 />"),
            ("mt:CGIHost\tMT Function", "mt:CGIHost$1 />"),
            ("mt:CGIPath\tMT Function", "mt:CGIPath$1 />"),
            ("mt:CGIRelativeURL\tMT Function", "mt:CGIRelativeURL$1 />"),
            ("mt:CGIServerPath\tMT Function", "mt:CGIServerPath$1 />"),
            ("mt:CalendarCellNumber\tMT Function", "mt:CalendarCellNumber$1 />"),
            ("mt:CalendarDate\tMT Function", "mt:CalendarDate$1 />"),
            ("mt:CalendarDay\tMT Function", "mt:CalendarDay$1 />"),
            ("mt:CaptchaFields\tMT Function", "mt:CaptchaFields$1 />"),
            ("mt:CategoryArchiveLink\tMT Function", "mt:CategoryArchiveLink$1 />"),
            ("mt:CategoryBasename\tMT Function", "mt:CategoryBasename$1 />"),
            ("mt:CategoryCommentCount\tMT Function", "mt:CategoryCommentCount$1 />"),
            ("mt:CategoryCount\tMT Function", "mt:$1 />"),
            ("mt:CategoryCustomFieldDescription\tMT Function", "mt:CategoryCustomFieldDescription$1 />"),
            ("mt:CategoryCustomFieldName\tMT Function", "mt:CategoryCustomFieldName$1 />"),
            ("mt:CategoryCustomFieldValue\tMT Function", "mt:CategoryCustomFieldValue$1 />"),
            ("mt:CategoryDescription\tMT Function", "mt:CategoryDescription$1 />"),
            ("mt:CategoryID\tMT Function", "mt:CategoryID$1 />"),
            ("mt:CategoryLabel\tMT Function", "mt:CategoryLabel$1 />"),
            ("mt:CategoryTrackbackCount\tMT Function", "mt:CategoryTrackbackCount$1 />"),
            ("mt:CategoryTrackbackLink\tMT Function", "mt:CategoryTrackbackLink$1 />"),
            ("mt:CommentAuthor\tMT Function", "mt:CommentAuthor$1 />"),
            ("mt:CommentAuthorIdentity\tMT Function", "mt:CommentAuthorIdentity$1 />"),
            ("mt:CommentAuthorLink\tMT Function", "mt:CommentAuthorLink$1 />"),
            ("mt:CommentBlogID\tMT Function", "mt:CommentBlogID$1 />"),
            ("mt:CommentBody\tMT Function", "mt:CommentBody$1 />"),
            ("mt:CommentCustomFieldDescription\tMT Function", "mt:CommentCustomFieldDescription$1 />"),
            ("mt:CommentCustomFieldName\tMT Function", "mt:CommentCustomFieldName$1 />"),
            ("mt:CommentCustomFieldValue\tMT Function", "mt:CommentCustomFieldValue$1 />"),
            ("mt:CommentDate\tMT Function", "mt:CommentDate$1 />"),
            ("mt:CommentEmail\tMT Function", "mt:CommentEmail$1 />"),
            ("mt:CommentEntry\tMT Function", "mt:CommentEntry$1 />"),
            ("mt:CommentEntryID\tMT Function", "mt:CommentEntryID$1 />"),
            ("mt:CommentID\tMT Function", "mt:CommentID$1 />"),
            ("mt:CommentIP\tMT Function", "mt:CommentIP$1 />"),
            ("mt:CommentLink\tMT Function", "mt:CommentLink$1 />"),
            ("mt:CommentName\tMT Function", "mt:CommentName$1 />"),
            ("mt:CommentOrderNumber\tMT Function", "mt:CommentOrderNumber$1 />"),
            ("mt:CommentParentID\tMT Function", "mt:CommentParentID$1 />"),
            ("mt:CommentPreviewAuthor\tMT Function", "mt:CommentPreviewAuthor$1 />"),
            ("mt:CommentPreviewAuthorLink\tMT Function", "mt:CommentPreviewAuthorLink$1 />"),
            ("mt:CommentPreviewBody\tMT Function", "mt:CommentPreviewBody$1 />"),
            ("mt:CommentPreviewDate\tMT Function", "mt:CommentPreviewDate$1 />"),
            ("mt:CommentPreviewEmail\tMT Function", "mt:CommentPreviewEmail$1 />"),
            ("mt:CommentPreviewIP\tMT Function", "mt:CommentPreviewIP$1 />"),
            ("mt:CommentPreviewIsStatic\tMT Function", "mt:CommentPreviewIsStatic$1 />"),
            ("mt:CommentPreviewURL\tMT Function", "mt:CommentPreviewURL$1 />"),
            ("mt:CommentRank\tMT Function", "mt:CommentRank$1 />"),
            ("mt:CommentRepliesRecurse\tMT Function", "mt:CommentRepliesRecurse$1 />"),
            ("mt:CommentScore\tMT Function", "mt:CommentScore$1 />"),
            ("mt:CommentScoreAvg\tMT Function", "mt:CommentScoreAvg$1 />"),
            ("mt:CommentScoreCount\tMT Function", "mt:CommentScoreCount$1 />"),
            ("mt:CommentScoreHigh\tMT Function", "mt:CommentScoreHigh$1 />"),
            ("mt:CommentScoreLow\tMT Function", "mt:CommentScoreLow$1 />"),
            ("mt:CommentScript\tMT Function", "mt:CommentScript$1 />"),
            ("mt:CommentURL\tMT Function", "mt:CommentURL$1 />"),
            ("mt:CommenterAuthIconURL\tMT Function", "mt:CommenterAuthIconURL$1 />"),
            ("mt:CommenterAuthType\tMT Function", "mt:CommenterAuthType$1 />"),
            ("mt:CommenterEmail\tMT Function", "mt:CommenterEmail$1 />"),
            ("mt:CommenterID\tMT Function", "mt:CommenterID$1 />"),
            ("mt:CommenterName\tMT Function", "mt:CommenterName$1 />"),
            ("mt:CommenterNameThunk\tMT Function", "mt:CommenterNameThunk$1 />"),
            ("mt:CommenterURL\tMT Function", "mt:CommenterURL$1 />"),
            ("mt:CommenterUsername\tMT Function", "mt:CommenterUsername$1 />"),
            ("mt:CommenterUserpic\tMT Function", "mt:CommenterUserpic$1 />"),
            ("mt:CommenterUserpicURL\tMT Function", "mt:CommenterUserpicURL$1 />"),
            ("mt:CommunityScript\tMT Function", "mt:CommunityScript$1 />"),
            ("mt:ConfigFile\tMT Function", "mt:ConfigFile$1 />"),
            ("mt:CurrentPage\tMT Function", "mt:CurrentPage$1 />"),
            ("mt:CustomFieldBasename\tMT Function", "mt:CustomFieldBasename$1 />"),
            ("mt:CustomFieldDescription\tMT Function", "mt:CustomFieldDescription$1 />"),
            ("mt:CustomFieldHTML\tMT Function", "mt:CustomFieldHTML$1 />"),
            ("mt:CustomFieldName\tMT Function", "mt:CustomFieldName$1 />"),
            ("mt:CustomFieldValue\tMT Function", "mt:CustomFieldValue$1 />"),
            ("mt:Date\tMT Function", "mt:Date$1 />"),
            ("mt:DefaultLanguage\tMT Function", "mt:DefaultLanguage$1 />"),
            ("mt:EntriesCount\tMT Function", "mt:EntriesCount$1 />"),
            ("mt:EntryAtomID\tMT Function", "mt:EntryAtomID$1 />"),
            ("mt:EntryAudio\tMT Function", "mt:EntryAudio$1 />"),
            ("mt:EntryAuthor\tMT Function", "mt:EntryAuthor$1 />"),
            ("mt:EntryAuthorDisplayName\tMT Function", "mt:EntryAuthorDisplayName$1 />"),
            ("mt:EntryAuthorEmail\tMT Function", "mt:EntryAuthorEmail$1 />"),
            ("mt:EntryAuthorID\tMT Function", "mt:EntryAuthorID$1 />"),
            ("mt:EntryAuthorLink\tMT Function", "mt:EntryAuthorLink$1 />"),
            ("mt:EntryAuthorNickname\tMT Function", "mt:EntryAuthorNickname$1 />"),
            ("mt:EntryAuthorURL\tMT Function", "mt:EntryAuthorURL$1 />"),
            ("mt:EntryAuthorUsername\tMT Function", "mt:EntryAuthorUsername$1 />"),
            ("mt:EntryAuthorUserpic\tMT Function", "mt:EntryAuthorUserpic$1 />"),
            ("mt:EntryAuthorUserpicURL\tMT Function", "mt:EntryAuthorUserpicURL$1 />"),
            ("mt:EntryBasename\tMT Function", "mt:EntryBasename$1 />"),
            ("mt:EntryBlogDescription\tMT Function", "mt:EntryBlogDescription$1 />"),
            ("mt:EntryBlogID\tMT Function", "mt:EntryBlogID$1 />"),
            ("mt:EntryBlogName\tMT Function", "mt:EntryBlogName$1 />"),
            ("mt:EntryBlogURL\tMT Function", "mt:EntryBlogURL$1 />"),
            ("mt:EntryBody\tMT Function", "mt:EntryBody$1 />"),
            ("mt:EntryCategory\tMT Function", "mt:EntryCategory$1 />"),
            ("mt:EntryClass\tMT Function", "mt:EntryClass$1 />"),
            ("mt:EntryClassLabel\tMT Function", "mt:EntryClassLabel$1 />"),
            ("mt:EntryCommentCount\tMT Function", "mt:EntryCommentCount$1 />"),
            ("mt:EntryCreatedDate\tMT Function", "mt:EntryCreatedDate$1 />"),
            ("mt:EntryCustomFieldDescription\tMT Function", "mt:EntryCustomFieldDescription$1 />"),
            ("mt:EntryCustomFieldName\tMT Function", "mt:EntryCustomFieldName$1 />"),
            ("mt:EntryCustomFieldValue\tMT Function", "mt:EntryCustomFieldValue$1 />"),
            ("mt:EntryDate\tMT Function", "mt:EntryDate$1 />"),
            ("mt:EntryEditLink\tMT Function", "mt:EntryEditLink$1 />"),
            ("mt:EntryEmbedCode\tMT Function", "mt:EntryEmbedCode$1 />"),
            ("mt:EntryExcerpt\tMT Function", "mt:EntryExcerpt$1 />"),
            ("mt:EntryFlag\tMT Function", "mt:EntryFlag$1 />"),
            ("mt:EntryID\tMT Function", "mt:EntryID$1 />"),
            ("mt:EntryKeywords\tMT Function", "mt:EntryKeywords$1 />"),
            ("mt:EntryLink\tMT Function", "mt:EntryLink$1 />"),
            ("mt:EntryLinkURL\tMT Function", "mt:EntryLinkURL$1 />"),
            ("mt:EntryModifiedDate\tMT Function", "mt:EntryModifiedDate$1 />"),
            ("mt:EntryMore\tMT Function", "mt:EntryMore$1 />"),
            ("mt:EntryPermalink\tMT Function", "mt:EntryPermalink$1 />"),
            ("mt:EntryPhoto\tMT Function", "mt:EntryPhoto$1 />"),
            ("mt:EntryPostType\tMT Function", "mt:EntryPostType$1 />"),
            ("mt:EntryRank\tMT Function", "mt:EntryRank$1 />"),
            ("mt:EntryRawPostType\tMT Function", "mt:EntryRawPostType$1 />"),
            ("mt:EntryRecommendVoteLink\tMT Function", "mt:EntryRecommendVoteLink$1 />"),
            ("mt:EntryRecommendedTotal\tMT Function", "mt:EntryRecommendedTotal$1 />"),
            ("mt:EntryScore\tMT Function", "mt:EntryScore$1 />"),
            ("mt:EntryScoreAvg\tMT Function", "mt:EntryScoreAvg$1 />"),
            ("mt:EntryScoreCount\tMT Function", "mt:EntryScoreCount$1 />"),
            ("mt:EntryScoreHigh\tMT Function", "mt:EntryScoreHigh$1 />"),
            ("mt:EntryScoreLow\tMT Function", "mt:EntryScoreLow$1 />"),
            ("mt:EntryStatus\tMT Function", "mt:EntryStatus$1 />"),
            ("mt:EntryTitle\tMT Function", "mt:EntryTitle$1 />"),
            ("mt:EntryTrackbackCount\tMT Function", "mt:EntryTrackbackCount$1 />"),
            ("mt:EntryTrackbackData\tMT Function", "mt:EntryTrackbackData$1 />"),
            ("mt:EntryTrackbackID\tMT Function", "mt:EntryTrackbackID$1 />"),
            ("mt:EntryTrackbackLink\tMT Function", "mt:EntryTrackbackLink$1 />"),
            ("mt:ErrorMessage\tMT Function", "mt:ErrorMessage$1 />"),
            ("mt:FeedEntryLink\tMT Function", "mt:FeedEntryLink$1 />"),
            ("mt:FeedEntryTitle\tMT Function", "mt:FeedEntryTitle$1 />"),
            ("mt:FeedInclude\tMT Function", "mt:FeedInclude$1 />"),
            ("mt:FeedLink\tMT Function", "mt:FeedLink$1 />"),
            ("mt:FeedTitle\tMT Function", "mt:FeedTitle$1 />"),
            ("mt:FeedbackScore\tMT Function", "mt:FeedbackScore$1 />"),
            ("mt:FileCustomFieldDescription\tMT Function", "mt:FileCustomFieldDescription$1 />"),
            ("mt:FileCustomFieldName\tMT Function", "mt:FileCustomFieldName$1 />"),
            ("mt:FileCustomFieldValue\tMT Function", "mt:FileCustomFieldValue$1 />"),
            ("mt:FileTemplate\tMT Function", "mt:FileTemplate$1 />"),
            ("mt:FolderBasename\tMT Function", "mt:FolderBasename$1 />"),
            ("mt:FolderCount\tMT Function", "mt:FolderCount$1 />"),
            ("mt:FolderCustomFieldDescription\tMT Function", "mt:FolderCustomFieldDescription$1 />"),
            ("mt:FolderCustomFieldName\tMT Function", "mt:FolderCustomFieldName$1 />"),
            ("mt:FolderCustomFieldValue\tMT Function", "mt:FolderCustomFieldValue$1 />"),
            ("mt:FolderDescription\tMT Function", "mt:FolderDescription$1 />"),
            ("mt:FolderID\tMT Function", "mt:FolderID$1 />"),
            ("mt:FolderLabel\tMT Function", "mt:FolderLabel$1 />"),
            ("mt:FolderPath\tMT Function", "mt:FolderPath$1 />"),
            ("mt:GetVar\tMT Function", "mt:GetVar$1 />"),
            ("mt:HTTPContentType\tMT Function", "mt:HTTPContentType$1 />"),
            ("mt:IfEntryRecommended\tMT Function", "mt:IfEntryRecommended$1 />"),
            ("mt:ImageCustomFieldDescription\tMT Function", "mt:ImageCustomFieldDescription$1 />"),
            ("mt:ImageCustomFieldName\tMT Function", "mt:ImageCustomFieldName$1 />"),
            ("mt:ImageCustomFieldValue\tMT Function", "mt:ImageCustomFieldValue$1 />"),
            ("mt:ImageHeight\tMT Function", "mt:ImageHeight$1 />"),
            ("mt:ImageURL\tMT Function", "mt:ImageURL$1 />"),
            ("mt:ImageWidth\tMT Function", "mt:ImageWidth$1 />"),
            ("mt:Include\tMT Function", "mt:Include$1 />"),
            ("mt:IndexBasename\tMT Function", "mt:IndexBasename$1 />"),
            ("mt:IndexLink\tMT Function", "mt:$1 />"),
            ("mt:IndexName\tMT Function", "mt:IndexName$1 />"),
            ("mt:Link\tMT Function", "mt:Link$1 />"),
            ("mt:MaxResults\tMT Function", "mt:MaxResults$1 />"),
            ("mt:NextLink\tMT Function", "mt:NextLink$1 />"),
            ("mt:NotifyScript\tMT Function", "mt:NotifyScript$1 />"),
            ("mt:OtherProfileVar\tMT Function", "mt:OtherProfileVar$1 />"),
            ("mt:PageAuthorDisplayName\tMT Function", "mt:PageAuthorDisplayName$1 />"),
            ("mt:PageAuthorEmail\tMT Function", "mt:PageAuthorEmail$1 />"),
            ("mt:PageAuthorLink\tMT Function", "mt:PageAuthorLink$1 />"),
            ("mt:PageAuthorURL\tMT Function", "mt:PageAuthorURL$1 />"),
            ("mt:PageBasename\tMT Function", "mt:PageBasename$1 />"),
            ("mt:PageBody\tMT Function", "mt:PageBody$1 />"),
            ("mt:PageCustomFieldDescription\tMT Function", "mt:PageCustomFieldDescription$1 />"),
            ("mt:PageCustomFieldName\tMT Function", "mt:PageCustomFieldName$1 />"),
            ("mt:PageCustomFieldValue\tMT Function", "mt:PageCustomFieldValue$1 />"),
            ("mt:PageDate\tMT Function", "mt:PageDate$1 />"),
            ("mt:PageExcerpt\tMT Function", "mt:PageExcerpt$1 />"),
            ("mt:PageID\tMT Function", "mt:PageID$1 />"),
            ("mt:PageKeywords\tMT Function", "mt:PageKeywords$1 />"),
            ("mt:PageModifiedDate\tMT Function", "mt:PageModifiedDate$1 />"),
            ("mt:PageMore\tMT Function", "mt:PageMore$1 />"),
            ("mt:PagePermalink\tMT Function", "mt:PagePermalink$1 />"),
            ("mt:PageTitle\tMT Function", "mt:PageTitle$1 />"),
            ("mt:PagerLink\tMT Function", "mt:PagerLink$1 />"),
            ("mt:PasswordValidation\tMT Function", "mt:PasswordValidation$1 />"),
            ("mt:PasswordValidationRule\tMT Function", "mt:PasswordValidationRule$1 />"),
            ("mt:PingBlogName\tMT Function", "mt:PingBlogName$1 />"),
            ("mt:PingDate\tMT Function", "mt:PingDate$1 />"),
            ("mt:PingExcerpt\tMT Function", "mt:PingExcerpt$1 />"),
            ("mt:PingID\tMT Function", "mt:PingID$1 />"),
            ("mt:PingIP\tMT Function", "mt:PingIP$1 />"),
            ("mt:PingRank\tMT Function", "mt:PingRank$1 />"),
            ("mt:PingScore\tMT Function", "mt:PingScore$1 />"),
            ("mt:PingScoreAvg\tMT Function", "mt:PingScoreAvg$1 />"),
            ("mt:PingScoreCount\tMT Function", "mt:PingScoreCount$1 />"),
            ("mt:PingScoreHigh\tMT Function", "mt:PingScoreHigh$1 />"),
            ("mt:PingScoreLow\tMT Function", "mt:PingScoreLow$1 />"),
            ("mt:PingTitle\tMT Function", "mt:PingTitle$1 />"),
            ("mt:PingURL\tMT Function", "mt:PingURL$1 />"),
            ("mt:PingsSentURL\tMT Function", "mt:PingsSentURL$1 />"),
            ("mt:PreviousLink\tMT Function", "mt:PreviousLink$1 />"),
            ("mt:ProductName\tMT Function", "mt:ProductName$1 />"),
            ("mt:PublishCharset\tMT Function", "mt:PublishCharset$1 />"),
            ("mt:RemoteSignInLink\tMT Function", "mt:RemoteSignInLink$1 />"),
            ("mt:RemoteSignOutLink\tMT Function", "mt:RemoteSignOutLink$1 />"),
            ("mt:SearchIncludeBlogs\tMT Function", "mt:SearchIncludeBlogs$1 />"),
            ("mt:SearchMaxResults\tMT Function", "mt:SearchMaxResults$1 />"),
            ("mt:SearchResultCount\tMT Function", "mt:SearchResultCount$1 />"),
            ("mt:SearchResultsFooter\tMT Function", "mt:SearchResultsFooter$1 />"),
            ("mt:SearchResultsHeader\tMT Function", "mt:SearchResultsHeader$1 />"),
            ("mt:SearchScript\tMT Function", "mt:SearchScript$1 />"),
            ("mt:SearchString\tMT Function", "mt:SearchString$1 />"),
            ("mt:SearchTemplateID\tMT Function", "mt:SearchTemplateID$1 />"),
            ("mt:SetVar\tMT Function", "mt:SetVar$1 />"),
            ("mt:SignOnURL\tMT Function", "mt:SignOnURL$1 />"),
            ("mt:SmartyPantsVersion\tMT Function", "mt:SmartyPantsVersion$1 />"),
            ("mt:StaticFilePath\tMT Function", "mt:StaticFilePath$1 />"),
            ("mt:StaticWebPath\tMT Function", "mt:StaticWebPath$1 />"),
            ("mt:StreamAction\tMT Function", "mt:StreamAction$1 />"),
            ("mt:StreamActionDate\tMT Function", "mt:StreamActionDate$1 />"),
            ("mt:StreamActionID\tMT Function", "mt:StreamActionID$1 />"),
            ("mt:StreamActionModifiedDate\tMT Function", "mt:StreamActionModifiedDate$1 />"),
            ("mt:StreamActionThumbnailURL\tMT Function", "mt:StreamActionThumbnailURL$1 />"),
            ("mt:StreamActionTitle\tMT Function", "mt:StreamActionTitle$1 />"),
            ("mt:StreamActionVar\tMT Function", "mt:StreamActionVar$1 />"),
            ("mt:SubCategoryPath\tMT Function", "mt:SubCategoryPath$1 />"),
            ("mt:SubCatsRecurse\tMT Function", "mt:SubCatsRecurse$1 />"),
            ("mt:SubFolderRecurse\tMT Function", "mt:SubFolderRecurse$1 />"),
            ("mt:SupportDirectoryURL\tMT Function", "mt:SupportDirectoryURL$1 />"),
            ("mt:TagCount\tMT Function", "mt:TagCount$1 />"),
            ("mt:TagID\tMT Function", "mt:TagID$1 />"),
            ("mt:TagLabel\tMT Function", "mt:TagLabel$1 />"),
            ("mt:TagName\tMT Function", "mt:TagName$1 />"),
            ("mt:TagRank\tMT Function", "mt:TagRank$1 />"),
            ("mt:TagSearchLink\tMT Function", "mt:TagSearchLink$1 />"),
            ("mt:TemplateCreatedOn\tMT Function", "mt:TemplateCreatedOn$1 />"),
            ("mt:TemplateCustomFieldDescription\tMT Function", "mt:TemplateCustomFieldDescription$1 />"),
            ("mt:TemplateCustomFieldName\tMT Function", "mt:TemplateCustomFieldName$1 />"),
            ("mt:TemplateCustomFieldValue\tMT Function", "mt:TemplateCustomFieldValue$1 />"),
            ("mt:TemplateNote\tMT Function", "mt:TemplateNote$1 />"),
            ("mt:TextileHeadOffset\tMT Function", "mt:TextileHeadOffset$1 />"),
            ("mt:TextileOptions\tMT Function", "mt:TextileOptions$1 />"),
            ("mt:TotalPages\tMT Function", "mt:TotalPages$1 />"),
            ("mt:TrackbackScript\tMT Function", "mt:TrackbackScript$1 />"),
            ("mt:TypeKeyToken\tMT Function", "mt:TypeKeyToken$1 />"),
            ("mt:Var\tMT Function", "mt:Var$1 />"),
            ("mt:Version\tMT Function", "mt:Version$1 />"),
            ("mt:VideoCustomFieldDescription\tMT Function", "mt:VideoCustomFieldDescription$1 />"),
            ("mt:VideoCustomFieldName\tMT Function", "mt:VideoCustomFieldName$1 />"),
            ("mt:VideoCustomFieldValue\tMT Function", "mt:VideoCustomFieldValue$1 />"),
            ("mt:WebsiteCCLicenseImage\tMT Function", "mt:WebsiteCCLicenseImage$1 />"),
            ("mt:WebsiteCCLicenseURL\tMT Function", "mt:WebsiteCCLicenseURL$1 />"),
            ("mt:WebsiteCommentCount\tMT Function", "mt:WebsiteCommentCount$1 />"),
            ("mt:WebsiteCustomFieldDescription\tMT Function", "mt:WebsiteCustomFieldDescription$1 />"),
            ("mt:WebsiteCustomFieldName\tMT Function", "mt:WebsiteCustomFieldName$1 />"),
            ("mt:WebsiteCustomFieldValue\tMT Function", "mt:WebsiteCustomFieldValue$1 />"),
            ("mt:WebsiteDescription\tMT Function", "mt:WebsiteDescription$1 />"),
            ("mt:WebsiteFileExtension\tMT Function", "mt:WebsiteFileExtension$1 />"),
            ("mt:WebsiteHasBlog\tMT Function", "mt:WebsiteHasBlog$1 />"),
            ("mt:WebsiteHost\tMT Function", "mt:WebsiteHost$1 />"),
            ("mt:WebsiteID\tMT Function", "mt:WebsiteID$1 />"),
            ("mt:WebsiteLanguage\tMT Function", "mt:WebsiteLanguage$1 />"),
            ("mt:WebsiteName\tMT Function", "mt:WebsiteName$1 />"),
            ("mt:WebsitePageCount\tMT Function", "mt:WebsitePageCount$1 />"),
            ("mt:WebsitePath\tMT Function", "mt:WebsitePath$1 />"),
            ("mt:WebsitePingCount\tMT Function", "mt:WebsitePingCount$1 />"),
            ("mt:WebsiteRelativeURL\tMT Function", "mt:WebsiteRelativeURL$1 />"),
            ("mt:WebsiteThemeID\tMT Function", "mt:WebsiteThemeID$1 />"),
            ("mt:WebsiteTimezone\tMT Function", "mt:WebsiteTimezone$1 />"),
            ("mt:WebsiteURL\tMT Function", "mt:WebsiteURL$1 />"),
            ("mt:WidgetManager\tMT Function", "mt:WidgetManager$1 />"),
            ("mt:WidgetSet\tMT Function", "mt:WidgetSet$1 />"),
            ("mt:XMLRPCScript\tMT Function", "mt:XMLRPCScript$1 />")
        ], sublime.INHIBIT_WORD_COMPLETIONS | sublime.INHIBIT_EXPLICIT_COMPLETIONS)
